export type Pericia =
   "Acrobacia"
   "Arcanismo"
   "Atletismo"
   "Atuação"
   "Blefar"
   "Furtividade"
   "História"
   "Intimidação"
   "Intuição"
   "Investigação"
   "Lidar com animais"
   "Medicina"
   "Natureza"
   "Percepção"
   "Persuasão"
   "Prestidigitação"
   "Religião"
   "Sobrevivência"
